---
title: Genus level conservation gap analysis summary
author: Daniel P. Carver and Colin K. Khoury 
output:
  html_document:
      css: style.css
date: "Report generated on `r Sys.Date()`"
params:
  reportData: NA
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
pacman::p_load("leaflet","data.table", "tidyr", "dplyr","plotly","DT")

### function for control number of character after the decimal place 
sigfig <- function(vec, n=3){ 
### function to round values to N significant digits
# input:   vec       vector of numeric
#          n         integer is the required sigfig  
# output:  outvec    vector of numeric rounded to N sigfig

formatC(signif(vec,digits=n), digits=n,format="fg", flag="#") 

} 



# transform data
# data <- conservationSummary$summaryData # testing only 
# figures <- conservationSummary$figure

data <- params$reportData$summaryData
figure <- params$reportData$figure
image <- params$reportData$map
```

## Conserveration Assessment 

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.align='right',out.width="100%"}
figure
```

## summary table 
```{r  echo=FALSE, message=FALSE, warning=FALSE}
# # alter Counts data for better visualizations
c1 <- data %>%
  select(Taxon = ID, everything()) %>%
  dplyr::mutate(Taxon = stringr::str_replace_all(Taxon, pattern = "_", replacement = " "))
  
c1[,2:12] <- lapply(c1[,2:12], sigfig)

DT::datatable(c1,
              rownames = FALSE,
              class = "compact")

```

## Map of Species Density 

```{r echo=FALSE, message=FALSE, warning=FALSE}
r1 <- raster(image)
r1[r1==0] <- NA
#distribution palette 
distColor <- c("#ffffd4","#fed98e","#fe9929","#d95f0e","#993404")
vals <- unique(values(r1))

# Mean distribution map 
meanPal <- colorNumeric(palette = distColor,domain = values(r1), na.color = "transparent")

leaflet(width = "100%")%>%
  addTiles()%>%
  addRasterImage(x = r1, 
                 colors = meanPal,
                 method = "ngb",
                 group = "Species Richness")%>%
  addLegend(position = "bottomright",
            color = distColor,
            title = "Species Richness",
            labels = c("1","","","",max(vals,na.rm = TRUE)),
            group = "Mean Distribution Model")
```